- become: 'yes'
  hosts: localhost
  name: Generate ansible file
  tasks:
  - ansible.builtin.package:
      name:
      - python3
      - nginx
      state: present
    name: Install packages
  - ansible.builtin.shell: cp ../ex00/exploit.py ../ex01/consumer.py ./
    name: Copy files
  - ansible.builtin.shell: python3 ./exploit.py ./consumer.py --bad-guys 4815162342,3133780085
    name: Execute files
