- name: excercize
  hosts: localhost
  become: yes

  tasks:
  - name: Install packages
    ansible.builtin.package: 
      name: 
        - python3
        - nginx
      state: present
  - name: Copy files
    ansible.builtin.copy:
      src: ./gen_ansible.py
      dest: ../gen_ansible.py
  - name: Execute files
    ansible.builtin.shell: python3 ../ex00/exploit.py
    